---
- name: Configure Wireless Access Point
  hosts: localhost
  become: yes
  vars:
    ssid: "{{ ssid }}"
  tasks:
    - name: Check if connected to Wi-Fi
      command: iwgetid -r
      register: wifi_ssid
      ignore_errors: yes

    - name: Disconnect from Wi-Fi if connected
      command: nmcli connection down "{{ wifi_ssid.stdout }}"
      when: wifi_ssid.stdout is defined
      ignore_errors: yes
    
    - name: Install necessary packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - hostapd
        - isc-dhcp-server

    - name: Stop hostapd and dhcp server services
      service:
        name: "{{ item }}"
        state: stopped
      loop:
        - isc-dhcp-server
        - hostapd

    - name: Check if DHCP process exists
      shell: ps aux | grep dhcp | grep -v grep
      register: dhcp_process
      ignore_errors: yes

    - name: Kill DHCP process if it exists
      shell: "kill -9 {{ dhcp_process.stdout.split()[1] }}"
      when: dhcp_process.stdout is defined
      ignore_errors: yes

    - name: Remove DHCP PID file
      file:
        path: /var/run/dhcp.pid
        state: absent
      when: dhcp_process.stdout is defined
      ignore_errors: yes

    - name: Configure DHCP server
      lineinfile:
        path: /etc/dhcp/dhcpd.conf
        line: "{{ item }}"
      loop:
        - "subnet 192.168.1.0 netmask 255.255.255.0 {"
        - "  range 192.168.1.10 192.168.1.50;"
        - "  option broadcast-address 192.168.1.255;"
        - "  option routers 192.168.1.1;"
        - "  default-lease-time 600;"
        - "  max-lease-time 7200;"
        - "  option domain-name \"local\";"
        - "  option domain-name-servers 8.8.8.8, 8.8.4.4;"
        - "}"
        

    - name: Configure network interface
      lineinfile:
        path: /etc/network/interfaces
        line: "{{ item }}"
      loop:
        - "allow-hotplug wlan0"
        - "iface wlan0 inet static"
        - "address 192.168.1.1"
        - "netmask 255.255.255.0"

    - name: Restart networking service
      service:
        name: networking
        state: restarted
      
    - name: Remove existing IP configuration from wlan0
      command: ip address flush dev wlan0
      ignore_errors: yes

    - name: Set static IP address
      command: ip address add 192.168.1.1/24 broadcast 192.168.1.255 dev wlan0

    - name: Configure hostapd
      copy:
        dest: /etc/hostapd/hostapd.conf
        content: |
            interface=wlan0
            ssid={{ ssid }}
            hw_mode=g
            channel=6
            macaddr_acl=0
            auth_algs=1
            ignore_broadcast_ssid=0
            wpa=0

    - name: Update hostapd configuration file path
      lineinfile:
        path: /etc/default/hostapd
        line: "DAEMON_CONF='/etc/hostapd/hostapd.conf'"

    - name: Start hostapd and dhcp server services
      service:
        name: "{{ item }}"
        state: started
      loop:
        - isc-dhcp-server
        - hostapd

    - name: Enable hostapd and dhcp server at boot
      service:
        name: "{{ item }}"
        enabled: yes
      loop:
        - hostapd
        - isc-dhcp-server
